### ISSUE TITLE
Bad result in running concept graph on ARKITScene dataset

### ISSUE THREAD

**Issue by JiaxiXie** [concept-graphs/concept-graphs#63]
I am now trying to run concept graph on ARKITScene dataset, and encountered a few problems. I have finished watching the tutorial and successfully generated the mapping  on [rerun.io](http://rerun.io/) using Replica Dataset.
Here are the changes I made for implementing concept map on ARKITScene dataset:
- I created a new ARKITScene Dataset class in `dataset/dataset_common.py` so that when `config_dict["dataset_name"] == 'arkitscene'` will do initialization with ARKITScene Dataset class.
- I created a `dataset/dataconfigs/arkitscene/arkitscene.yaml` file with following parameters
 ```
dataset_name: ‘arkitscene'
camera_params:
    image_height: 192
    image_width: 256
    fx: 212.027
    fy: 212.027
    cx: 127.933
    cy: 95.9333
    png_depth_scale: 6553.5
crop_edge: 0
```
I have done tests for all the above parameters by using them to generate Open3D simulation with only rgb_images and depth_images
  
<img width="299" alt="Screenshot 2024-08-07 at 23 05 04" src="https://github.com/user-attachments/assets/d93c9185-bbba-40fe-bb74-14b0750ea589">
	
- I created a `hydra_configs/arkitscene.yaml` to modify the path
- I have also checked the camera’s quaternions and translations line by line, and they are all correct
- I have tried the solution to "flip the sign for the Y and Z axes of the camera pose" that is mentioned by another issue with similar problem

Here is the problem: from the clip from [rerun.io](http://rerun.io/) below that there are overlapping of items. I am really not sure what causes those. I would definitely appreciate it if someone could share some opinions and suggestion on the problem. Thanks a lot.
<img width="254" alt="Screenshot 2024-08-07 at 23 08 33" src="https://github.com/user-attachments/assets/88b7c800-da25-4a70-b01b-939e26533076">
